#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

#########################
# Logentries streaming
#########################

# We export or own "openshift" env variable to stream rails log files
export OPENSHIFT_RAILS_LOG_DIR=${OPENSHIFT_REPO_DIR}/log

# Make sure the agent is an executable
chmod +x ${OPENSHIFT_REPO_DIR}script/logentries/le

# If the config exists, the agent is registered and following files
if [ ! -f "${OPENSHIFT_DATA_DIR}config" ];
then
	# Load the user config with Logentries Account Key
	source ${OPENSHIFT_REPO_DIR}script/logentries/le_config.ini

	${OPENSHIFT_REPO_DIR}script/logentries/le register --hostname=${OPENSHIFT_APP_NAME} --account-key=${ACCOUNT_KEY}
fi

# We don't want just OPENSHIFT_LOG_DIR as it could be a duplicate
for dir in `env | grep OPENSHIFT_.*_LOG_DIR`
do
	logdir=${dir#*=}
	for logf in `ls $logdir`
	do
		# We consider every file in these directories is a log file

		# Navigate to the log directory
        pushd $logdir > /dev/null

        # Follow any new logs and make sure existing ones are being followed
        ${OPENSHIFT_REPO_DIR}script/logentries/le follow "$logf"

        popd > /dev/null
	done
done

# Start monitoring the log files
${OPENSHIFT_REPO_DIR}script/logentries/le monitordaemon