#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "Disabling maintenance mode"
bundle exec rake maintenance:disable RAILS_ENV="production"
popd > /dev/null