#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "Stopping delayed_job"
RAILS_ENV=production script/delayed_job stop
popd > /dev/null
