#!/bin/bash

echo "`date` Started updating sessions" >> $OPENSHIFT_DATA_DIR/cron.log

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
RAILS_ENV=production rake data:update_sessions
popd > /dev/null

echo "`date` Finished updating sessions" >> $OPENSHIFT_DATA_DIR/cron.log