#!/bin/bash

echo "`date` - Launching a logs cleaning" >> $OPENSHIFT_DATA_DIR/cron.log

# Clean log files to save space (hopefully logentries will have streamed them to the cloud)
# Clean dumps files too (should be synced to dropbox)

# Delete old ruby log files
find ${OPENSHIFT_RUBY_LOG_DIR} -type f -mtime +14 -exec rm {} \;

# Clear mysql error file
# **** Commented out because does not almost grow in size... ****
# cp /dev/null ${OPENSHIFT_MYSQL_DB_LOG_DIR}/mysql_error.log

# Clean rails log files
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
RAILS_ENV=production rake logs:rotate &
popd > /dev/null

# Delete old sql dumps
find ${OPENSHIFT_DATA_DIR}/dumps -type f -name *.sql -mtime +7 -exec rm {} \;

echo "`date` Finished cleaning logs" >> $OPENSHIFT_DATA_DIR/cron.log