#!/bin/bash

echo "`date` Started updating grades" >> $OPENSHIFT_DATA_DIR/cron.log

day=`date "+%j"`
rem=$(( $day % 2 ))

if [ $rem -eq 0 ]
then
  pushd ${OPENSHIFT_REPO_DIR} > /dev/null
  RAILS_ENV=production rake data:update_grades
  popd > /dev/null
fi

echo "`date` Finished updating grades" >> $OPENSHIFT_DATA_DIR/cron.log