#!/bin/bash

echo "`date` Started updating absences" >> $OPENSHIFT_DATA_DIR/cron.log

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
RAILS_ENV=production rake data:update_absences
popd > /dev/null

echo "`date` Finished updating absences" >> $OPENSHIFT_DATA_DIR/cron.log