#!/bin/bash

echo "`date` Checking the need to update grades" >> $OPENSHIFT_DATA_DIR/cron.log

day=`date "+%j"`
rem=$(( $day % 2 ))

if [ $rem -eq 0 ]
then
  echo "`date` - Launching a grade update" >> $OPENSHIFT_DATA_DIR/cron.log

  pushd ${OPENSHIFT_REPO_DIR} > /dev/null
  RAILS_ENV=production rake data:update_grades &
  popd > /dev/null
fi