#!/bin/sh
echo "Restarting Puma"
script/puma.sh restart

echo "Restarting jobs"
RAILS_ENV=production PIDFILE=tmp/resque/resque.pid BACKGROUND=yes bundle exec rake environment QUEUE='critical,high,medium,low' resque:work