#!/bin/sh
echo "Restarting Puma"
script/puma.sh restart

echo "Updating cron"
bundle exec whenever --update-crontab

echo "Starting back jobs"
script/delayed_job --queue=regular -i=1 start
script/delayed_job --queues=regular,grades -i=2 start
