#!/bin/bash

echo "`date` Began delayed_job restart" >> $OPENSHIFT_DATA_DIR/cron.log

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
RAILS_ENV=production script/delayed_job restart
popd > /dev/null

echo "`date` Finished delayed_job restart" >> $OPENSHIFT_DATA_DIR/cron.log