#!/bin/bash

TIME=$(date '+%H%M%S' --utc)

if [ $TIME -ge 020000 ] && [ $TIME -le 025959 ]
then
    echo "`date` - Launching a schedule update" >> $OPENSHIFT_DATA_DIR/cron.log

    pushd ${OPENSHIFT_REPO_DIR} > /dev/null
    RAILS_ENV=production rake data:update_schedules &
    popd > /dev/null
fi

if [ $TIME -ge 140000 ] && [ $TIME -le 145959 ]
then
    echo "`date` - Launching a schedule update" >> $OPENSHIFT_DATA_DIR/cron.log

    pushd ${OPENSHIFT_REPO_DIR} > /dev/null
    RAILS_ENV=production rake data:update_schedules &
    popd > /dev/null
fi
